### ISSUE TITLE
Rinha de bequi endis 

### ISSUE THREAD

**Issue by AlcivanLucas** [richhh7g/rinha-de-backend-2024#9]
iai ! , conseguiu que sua API fosse testada pelo sistema do rinha de back-ends?

**Comment by richhh7g** [comment]
Vou subir até hoje a noite rsrs

**Comment by AlcivanLucas** [comment]
Estou com um probleminha na validação da concorrência de crédito/débito, no começo do teste quando ele faz aquelas 50 requisições iguais, parece que o db não atualiza o saldo corretamente, implementei um mecanismo de cache , e verificação de atualização do saldo, mas não resolveu

**Comment by richhh7g** [comment]
Pode ser que o Thread principal do node pode estar bloqueado, tu pode criar outro Thread para lidar com o banco em um Thread secundário, só toma cuidado para não ultrapassar o limite das specs da máquina que irá efetuar o teste.
https://www.digitalocean.com/community/tutorials/how-to-use-multithreading-in-node-js

Outra possibilidade e a transaction do banco utilizado, estar terminando uma execução em quanto outra pode estar entrando e bloqueado, tu pode mudar o comportamento de uma transaction caso ache necessário.
Ex no PG: https://www.postgresql.org/docs/current/sql-set-transaction.html

Pode ser várias possibilidades, tenta debugar toda sua aplicação e ver o que ela diz em detalhes e toma uma ação a partir disso.

**Comment by AlcivanLucas** [comment]
Queria ter conseguido fazer as alterações enquanto o evento ainda estava aberto para commit, tive um problema pessoal 😓, mas enquanto estava em viagem, me veio a cabeça esse questão do comportamento da transaction, estou usando um connection pool de 2, o que devia tá fazendo uma bagunça na fila de conexões do banco de dados

**Comment by richhh7g** [comment]
Relaxa man, na próxima rinha faremos melhor, quem sabe em conjunto kkk

**Comment by AlcivanLucas** [comment]
Agr é só esperar a live do dia 14 kkkk
